-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Oct 21, 2020 at 12:28 PM
-- Server version: 10.1.16-MariaDB
-- PHP Version: 7.0.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `shope5`
--

-- --------------------------------------------------------

--
-- Table structure for table `mains`
--

CREATE TABLE `mains` (
  `opr` int(11) NOT NULL,
  `idindex` varchar(10) NOT NULL,
  `itemname` varchar(500) NOT NULL,
  `itempics` varchar(500) NOT NULL,
  `price` varchar(20) NOT NULL,
  `features` varchar(1000) NOT NULL,
  `sellername` varchar(100) NOT NULL,
  `sellercontact` varchar(25) NOT NULL,
  `timestamp` varchar(150) NOT NULL,
  `wheres` varchar(10) NOT NULL DEFAULT 'back',
  `cat` varchar(50) NOT NULL,
  `sellerlocation` varchar(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `mains`
--

INSERT INTO `mains` (`opr`, `idindex`, `itemname`, `itempics`, `price`, `features`, `sellername`, `sellercontact`, `timestamp`, `wheres`, `cat`, `sellerlocation`) VALUES
(115, '2Q9H48APXP', 'core is hitech laptop computer', 'images/ccomputers2.jpg', '30000', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. \r\n', 'Dennis Karuga', '0708453589', '', 'back', 'computers', 'Nairobi'),
(116, 'MK3F903HT3', 'Mack Computer, high technology and intact', 'images/448179-microsoft-surface-studio_960x540.jpg', '90000', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'computers', 'Nairobi'),
(117, 'H6TJTAZZW5', 'All types of classic computers', 'images/f6.jpg', '20000', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'computers', 'Nairobi'),
(118, 'S38IK693IH', 'ordinary 500gb hp computer with sim slot', 'images/ccomputers.jpg', '35000', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'computers', 'Nairobi'),
(119, 'H2J5KC2YMX', 'ordinary 500gb hp computer with sim slot', 'images/ccomputers2.jpg', '15878', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'computers', 'Nairobi'),
(120, '88NWEWTQKT', 'Mack Computer, high technology and intact', 'images/448179-microsoft-surface-studio_960x540.jpg', '90000', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'computers', 'Nairobi'),
(121, 'RGYH7NBK9B', 'super smartphone with 2gb ram', 'images/s8.jpg', '15000', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'smartPhones', 'Nairobi'),
(122, 'HJIBQOWSP3', 'hand grip smartphone', 'images/f9.jpg', '12000', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'smartPhones', 'Nairobi'),
(123, '0OLAUGR46I', 'high defination 3d tablet', 'images/best_ipad_ipad_9.7_2018_960x540.jpg', '15878', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'smartPhones', 'Nairobi'),
(124, 'HXVC3TX7HK', 'Infinix Hot 4 with 5mega pixels rear camera', 'images/cphone.jpg', '12345', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'smartPhones', 'Nairobi'),
(125, 'H7VD9JTWYR', 'high defination 3d tablet', 'images/173559841_1_960x540.jpg', '12345', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'smartPhones', 'Nairobi'),
(126, 'A38LWO37WR', 'samsung galaxy s infinite', 'images/cphone.jpg', '12345', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'smartPhones', 'Nairobi'),
(127, 'B9YZRJNHTV', 'modern fashion full b dress', 'images/1_960x540.jpg', '15878', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'clothingsAndFash', 'Nairobi'),
(128, 'RVHTBG26FW', 'full cover style dressing', 'images/cdressing.jpg', '15878', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'clothingsAndFash', 'Nairobi'),
(129, 'E5VT9D8D8T', 'protocal women wear in black suit', 'images/s13.jpg', '1000', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'clothingsAndFash', 'Nairobi'),
(130, '68WB6JO8NH', 'amazing dress with matching flower', 'images/cdress2.jpg', '15878', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'clothingsAndFash', 'Nairobi'),
(131, '6BAV1AB1EJ', 'll modern dress figures with size suit', 'images/Untitled_960x540.png', '1000', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'clothingsAndFash', 'Nairobi'),
(132, 'VRDGWMJ2GR', 'high quality coocker with adjustment save', 'images/coocker.png', '15878', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'other', 'Nairobi'),
(133, 'G4O3CV0WZ3', 'loundry soaps and components for enhanced washing', 'images/claundry.png', '1000', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'other', 'Nairobi'),
(134, 'RJAY8ZH59W', 'high defination headset with set mordern freq', 'images/cheadphones.jpg', '12345', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'other', 'Nairobi'),
(135, 'EX6VKAYY5D', 'Routing components for enhanced data communication', 'images/cgadgets.jpg', '6000', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'other', 'Nairobi'),
(136, 'B8O31WUAHA', 'ready meal at affordable pricing', 'images/f7.jpg', '15878', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'other', 'Nairobi'),
(137, 'EPFG37A1UX', 'high class modern woofer with digital control', 'images/Best-Sub-Woofer-Speaker-Under-7K-in-Kenya-640x426.jpg', '5000', 'On the Insert tab, the galleries include\r\nitems that are designed to coordinate \r\nwith the overall look of your document. \r\nYou can use these galleries to insert \r\ntables, headers, footers, lists, cover \r\npages, and other document building blocks. ', 'Dennis Karuga', '0708453589', '', 'back', 'other', 'Nairobi'),
(138, '983Q0LHJ44', 'High definition camera with spare lenses attached to coupon', 'images/4bu26pa-hp-pavilion-x360-14-cd0007tu-14-inch-2-in-1-laptop_1_960x540.jpg', '15878', 'High definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'computers', 'Nairobi'),
(139, '25KRFCAH8Q', 'High definition camera with spare lenses attached to coupon', 'images/4bu26pa-hp-pavilion-x360-14-cd0007tu-14-inch-2-in-1-laptop_1_960x540.jpg', 'High defin', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'computers', 'Nairobi'),
(140, 'EWVN0RV1QB', 'High definition camera with spare lenses attached to coupon', 'images/4bu26pa-hp-pavilion-x360-14-cd0007tu-14-inch-2-in-1-laptop_1_960x540.jpg', '12000', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'computers', 'Nairobi'),
(141, 'AJCVG7QSRV', 'Full Dress with fashion stripes loaded in all sizes', 'images/1.jpg', '1000', 'Full Dress with fashion stripes loaded in all sizes\r\nFull Dress with fashion stripes loaded in all sizes\r\nFull Dress with fashion stripes loaded in all sizes', 'Dennis Karuga', '0708453589', '', 'back', 'clothingsAndFash', 'Nairobi'),
(142, '6WBW7YDNZS', 'High definition camera with spare lenses attached to coupon', 'images/4bu26pa-hp-pavilion-x360-14-cd0007tu-14-inch-2-in-1-laptop_1_960x540.jpg', '15878', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'computers', 'Nairobi'),
(143, 'LURZC7GH8B', 'High definition camera with spare lenses attached to coupon', 'images/4bu26pa-hp-pavilion-x360-14-cd0007tu-14-inch-2-in-1-laptop_1_960x540.jpg', '30000', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'computers', 'Nairobi'),
(144, 'MXRLI680BX', 'High definition laptop with spare lenses attached to coupon', 'images/4bu26pa-hp-pavilion-x360-14-cd0007tu-14-inch-2-in-1-laptop_1_960x540.jpg', 'High defin', 'High definition laptop with spare lenses attached to coupon\r\nHigh definition laptop with spare lenses attached to coupon\r\nHigh definition laptop with spare lenses attached to coupon\r\nHigh definition laptop with spare lenses attached to coupon\r\nHigh definition laptop with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'computers', 'Nairobi'),
(145, 'LBW3X0OX9Q', 'High definition laptop with spare lenses attached to coupon', 'images/4bu26pa-hp-pavilion-x360-14-cd0007tu-14-inch-2-in-1-laptop_1_960x540.jpg', 'High defin', 'High definition laptop with spare lenses attached to coupon\r\nHigh definition laptop with spare lenses attached to coupon\r\nHigh definition laptop with spare lenses attached to coupon\r\nHigh definition laptop with spare lenses attached to coupon\r\nHigh definition laptop with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'computers', 'Nairobi'),
(146, 'OUNQ19XKRC', 'High definition laptop with spare lenses attached to coupon', 'images/4bu26pa-hp-pavilion-x360-14-cd0007tu-14-inch-2-in-1-laptop_1_960x540.jpg', 'High defin', 'High definition laptop with spare lenses attached to coupon\r\nHigh definition laptop with spare lenses attached to coupon\r\nHigh definition laptop with spare lenses attached to coupon\r\nHigh definition laptop with spare lenses attached to coupon\r\nHigh definition laptop with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'computers', 'Nairobi'),
(147, '2P7031NNDS', 'High definition camera with spare lenses attached to coupon', 'images/camera.jpg', '15000', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'electronics', 'Nairobi'),
(148, '6EKQZ0OLAU', 'High definition camera with spare lenses attached to coupon', 'images/camera.jpg', '15000', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'electronics', 'Nairobi'),
(149, '23XEEE5VT9', 'High definition camera with spare lenses attached to coupon', 'images/camera.jpg', '15000', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'electronics', 'Nairobi'),
(150, 'J3TC768WB6', 'High definition camera with spare lenses attached to coupon', 'images/camera.jpg', '15000', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'electronics', 'Nairobi'),
(151, '43Q696BAV1', 'High definition camera with spare lenses attached to coupon', 'images/camera.jpg', '15000', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'electronics', 'Nairobi'),
(152, 'Q9Y74G4O3C', 'High definition camera with spare lenses attached to coupon', 'images/camera.jpg', '15000', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'electronics', 'Nairobi'),
(153, '1W3R6RJAY8', 'High definition camera with spare lenses attached to coupon', 'images/camera.jpg', '15000', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'electronics', 'Nairobi'),
(154, 'SCG8TEPFG3', 'High definition camera with spare lenses attached to coupon', 'images/camera.jpg', '15000', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'electronics', 'Nairobi'),
(155, '6LJFNNPDAV', 'High definition camera with spare lenses attached to coupon', 'images/camera.jpg', '15000', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'electronics', 'Nairobi'),
(156, 'KJPGOQBTRH', 'High definition camera with spare lenses attached to coupon', 'images/camera.jpg', '15000', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'electronics', 'Nairobi'),
(157, 'Y5X9Y09YCE', 'High definition camera with spare lenses attached to coupon', 'images/camera.jpg', '15000', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'electronics', 'Nairobi'),
(158, 'WZK7XYHSVG', 'High definition camera with spare lenses attached to coupon', 'images/camera.jpg', '15000', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'electronics', 'Nairobi'),
(160, 'BBRG978ZKA', 'High definition camera with spare lenses attached to coupon', 'images/camera.jpg', '15000', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'electronics', 'Nairobi'),
(161, 'ZZWZDVA8KU', 'High definition camera with spare lenses attached to coupon', 'images/camera.jpg', '15000', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'electronics', 'Nairobi'),
(162, 'EMZ97ZFITT', 'High definition camera with spare lenses attached to coupon', 'images/camera.jpg', '15000', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'electronics', 'Nairobi'),
(163, 'JT9L682ARE', 'High definition camera with spare lenses attached to coupon', 'images/camera.jpg', '15000', 'High definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon\r\nHigh definition camera with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'electronics', 'Nairobi'),
(164, 'DIQF6P6WBW', 'High definition camera connectors with spare lenses attached to coupon', 'images/cautoparts.jpg', '500', 'High definition camera connectors with spare lenses attached to coupon\r\nHigh definition camera connectors with spare lenses attached to coupon\r\nHigh definition camera connectors with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'autoparts', 'Nairobi'),
(165, 'T0POF57LVG', 'High definition tv with spare connectors attached to coupon', 'images/laptop.jpg', '24000', 'High definition camera connectors with spare lenses attached to coupon\r\nHigh definition camera connectors with spare lenses attached to coupon\r\nHigh definition camera connectors with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'tvs', 'Nairobi'),
(167, 'MVG9XY40A6', 'High definition tv with spare connectors attached to coupon', 'images/smartTV.jpg', '28000', 'High definition camera connectors with spare lenses attached to coupon\r\nHigh definition camera connectors with spare lenses attached to coupon\r\nHigh definition camera connectors with spare lenses attached to coupon', 'Dennis Karuga', '0708453589', '', 'back', 'tvs', 'Nairobi'),
(168, '76MVDCLIAG', 'samsung galaxy s infinite camera lens', 'images/sm1.jpg', '12000', 'samsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens', 'Dennis Karuga', '0708453589', '', 'back', 'smartPhones', 'Nairobi'),
(169, 'B55MRJYLZQ', 'High definition camera with spare lenses attached to coupon', 'images/sm6.jpg', '16000', 'samsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens', 'Dennis Karuga', '0708453589', '', 'back', 'smartPhones', 'Nairobi'),
(170, '7Q563QY7FD', 'High definition camera with spare lenses attached to coupon', 'images/sm6.jpg', '16000', 'samsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens', 'Dennis Karuga', '0708453589', '', 'back', 'smartPhones', 'Nairobi'),
(171, '5G7ML8MDNO', 'samsung galaxy s infinite camera lens', 'images/sm2.jpg', '30000', 'samsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens', 'Dennis Karuga', '0708453589', '', 'back', 'smartPhones', 'Nairobi'),
(172, '7VC7T10J0I', 'High definition camera with spare lenses attached to coupon', 'images/sm5.jpg', '17000', 'samsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens', 'Dennis Karuga', '0708453589', '', 'back', 'smartPhones', 'Nairobi'),
(173, '0DA3G6PTKT', 'High definition camera with spare lenses attached to coupon', 'images/sm3.jpg', '1000', 'samsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens', 'Dennis Karuga', '0708453589', '', 'back', 'smartPhones', 'Nairobi'),
(174, '5MPWR4KNYT', 'samsung galaxy s infinite camera lens', 'images/sm4.jpg', '20000', 'samsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens\r\nsamsung galaxy s infinite camera lens', 'Dennis Karuga', '0708453589', '', 'back', 'smartPhones', 'Nairobi'),
(175, 'B53V0HJIBQ', 'queen dress in flexible, ight color and dark, different sizes ', 'images/s13.jpg', '3000', 'queen dress in flexible, ight color and dark, different sizes \r\nqueen dress in flexible, ight color and dark, different sizes \r\nqueen dress in flexible, ight color and dark, different sizes ', 'Dennis Karuga', '0708453589', '', 'back', 'clothingsAndFash', 'Nairobi'),
(176, 'WRUNMJXKUR', 'the mordern ai camera with long life battery and lenses', 'images/camera.jpg', '18000', 'the mordern ai camera with long life battery and lenses\r\nthe mordern ai camera with long life battery and lenses\r\nthe mordern ai camera with long life battery and lenses', 'Dennis Karuga', '0708453589', '', 'back', 'electronics', 'Nairobi'),
(177, 'LPQWPLPZ2M', 'laptop computer with high processing speed and work', 'images/4bu26pa-hp-pavilion-x360-14-cd0007tu-14-inch-2-in-1-laptop_1_960x540.jpg', '17000', 'laptop computer with high processing speed and work\r\nlaptop computer with high processing speed and work\r\nlaptop computer with high processing speed and work', 'Dennis Karuga', '0708453589', '', 'back', 'computers', 'Nairobi'),
(178, 'VDCLIAGB55', 'High class Gadgets with functions', 'images/fibreoptic.jpg', '15000', 'High class Gadgets with functions\r\nHigh class Gadgets with functions\r\nHigh class Gadgets with functions\r\nHigh class Gadgets with functions', 'Dennis Karuga', '0708453589', '', 'back', 'computers', 'Nairobi');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `mains`
--
ALTER TABLE `mains`
  ADD PRIMARY KEY (`opr`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `mains`
--
ALTER TABLE `mains`
  MODIFY `opr` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=179;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
